Add Linux 5.15.152 grsec kernels
freedomofpress/securedrop-apt-test pull request #226
Opened 2024-03-29 14:14 UTC by rocodes

## Status

Ready for review

## Description of changes

Add Linux 5.15.152 grsec kernels (core and workstation)
(Note: kernels untested. Source tarballs retained.)

## Checklist
- [ ] Cross-link to changes made in [securedrop-builder](https://github.com/freedomofpress/securedrop-builder): n/a
- [x] Build logs have been committed to [build-logs](https://github.com/freedomofpress/build-logs): [f6dcbbe](https://github.com/freedomofpress/build-logs/commit/f6dcbbe20b3c01c5881e2c8c0c273af934580030)

2024-04-01 18:10 UTC, legoktm requested changes
* [x] Packages match buildinfo / build-logs lgtm
* [ ] missing upstream tarballs

2024-04-02 15:50 UTC, rocodes commented
Upstream tarballs have been uploaded

2024-04-02 16:38 UTC, legoktm approved these changes
woot

2024-04-02 16:38 UTC, merged

2024-04-03 15:35 UTC, rocodes commented
Kernels install successfully on 4.1 staging setup using the GUI updater, VMs boot, basic functionality is as expected